server:
  port: 9001

# App Properties
ctrends:
  app:
    jwtSecret: ctrendsSecretKey
    jwtExpirationMs: 172800000

spring:
  application:
    name: EMPLOYEE-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/ctrends
    username: postgres
    password: 1234
    initialization-mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
