server:
  port: 9001

# App Properties
ctrends:
  app:
    jwtSecret: ctrendsSecretKey
#    1 min = 60000 ms
#    24 h = 86400000 ms
#    48 h = 172800000 ms
    jwtExpirationMs: 172800000

spring:
  application:
    name: EMPLOYEE-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/ctrends
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
